[package]
name = "tl2"
version = "0.1.0"
authors = ["johnpyp <johnpyp.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.2"
futures = "0.3"
log = "0.4.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
tokio = { version = "0.2", features = ["full"] }
anyhow = "1.0"
config = "0.10.1"
pretty_env_logger = "0.4.0"
twitch-irc = { version = "1.0.0", features = ["transport-wss"] }
colored = "2.0.0"
chrono = { version = "0.4.19", features = ["serde"] }
lru = "0.6.3"
tokio-tungstenite = { version = "0.11.0", features = ["tls"] }
httparse = "1.3.4"
derive_more = "0.99.11"
enum_dispatch = "0.3.5"
strum = { version = "0.20.0", features = ["derive"] }
rand = "0.8.1"
elasticsearch = "7.10.0-alpha.1"
reqwest = { version = "0.10.10", features = ["json"] }
voca_rs = "1.13.0"
