version: "3.7"
services:
  clickhouse:
    image: yandex/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ${CLICKHOUSE_PATH:-./clickhouse-data}:/var/lib/clickhouse
      # - ./clickhouse-config.xml:/etc/clickhouse-server/config.xml
    ports:
      - 8123:8123
      - 9000:9000
    restart: unless-stopped
