version: "3"

services:
  scraper:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    environment:
      RUST_ENV: docker
      CONFIG_PATH: /app/config
    volumes:
      - ./config:/app/config
      - ${HOST_LOGS_PATH:-./logs}:/app/logs
      - ${HOST_CHANNELS_PATH:-./channels}:/app/channels
      - ${HOST_SQL_PATH:-./sql}:/app/sql
    tty: true
    init: true
    network_mode: host
    restart: unless-stopped
