---
debug: info
twitch:
  enabled: true
  use_websocket: true
  channels:
    adapter: Json
    path: "./channels/channels.json"
  sync_channels_interval: 30
discord_alerting:
  enabled: false
  webhook_url:
  owner:
dgg_like:
  max_retry_seconds: 120
  sites:
    - name: Destinygg
      endpoint: wss://chat.destiny.gg/ws
      origin: https://www.destiny.gg
      use_get_key: false
writers:
  elasticsearch:
    enabled: false
    host: http://localhost
    port: "9200"
    index: rustlesearch
    pipeline: rustlesearch-pipeline
    batch_size: 1000
    batch_period_seconds: 10
    max_retry_seconds: 360
  clickhouse:
    enabled: false
    url: "http://localhost:8123"
  filesystem:
    enabled: false
    path: "./logs"
  console:
    enabled: false
  console_metrics:
    enabled: true
  username_tracker:
    enabled: false
    sqlite_path: "./data/sql/main.db"
