---
twitch:
  channels:
    adapter: Json
    path: "/app/channels/channels.json"
writers:
  filesystem:
    path: "/app/logs"
  username_tracker:
    sqlite_path: "/app/sql/main.db"
    batch_size: 200
